#### [Source] : https://machinelearningmastery.com/index-slice-reshape-numpy-arrays-machine-learning-python/

- How to convert your list data to NumPy arrays. 
-  How to access data using Pythonic indexing and slicing.
- How to resize your data to meet the expectations of some machine learning APIs.

## 1. From List to Arrays

#### One-Dimensional List to Array

In [2]:
from numpy import array
data = [11, 22, 33, 44, 55]
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


#### Two-Dimensional List of Lists to Array

In [4]:
from numpy import array 
data = [[11, 22],
        [33, 44],
        [55, 66]]
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


## 2. Array Indexing

#### One-Dimensional Indexing

In [6]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[0])
print(data[4])
print(data[-1])
print(data[-5])

11
55
55
11


#### Two-Dimensional Indexing

In [12]:
from numpy import array
data = array([[11,22],[33, 44],[55, 66]])
print(data[0,0])
print(data[0,])

11
[11 22]


## 3. Array Slicing

#### One-Dimensional Slicing

In [15]:
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[:])
print(data[0:1])
print(data[-2:])

[11 22 33 44 55]
[11]
[44 55]


#### Two-Dimensional Slicing


It is common to split your loaded data into input variables (X) and the output variable (y).

We can do this by slicing all rows and all columns up to, but before the last column, then separately indexing the last column.

For the input features, we can select all rows and all columns except the last one by specifying ‘:’ for in the rows index, and :-1 in the columns index.

X = [:, :-1]
1
X = [:, :-1]
For the output column, we can select all rows again using ‘:’ and index just the last column by specifying the -1 index.

y = [:, -1]
1
y = [:, -1]

In [16]:
from numpy import array
data = array([[11, 22, 33],
              [44, 55, 66],
              [77, 88, 99]])
X,y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


It is common to split a loaded dataset into separate train and test sets.

This is a splitting of rows where some portion will be used to train the model and the remaining portion will be used to estimate the skill of the trained model.

This would involve slicing all columns by specifying ‘:’ in the second dimension index. The training dataset would be all rows from the beginning to the split point.

dataset
train = data[:split, :]

The test dataset would be all rows starting from the split point to the end of the dimension.

test = data[split:, :]


In [17]:
from numpy import array
data = array([[11, 22, 33],
              [44, 55, 66],
              [77, 88, 99]])
split = 2
train, test = data[:split, :], data[split:, :]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


## 4. Array Reshaping

In [18]:
# array shape
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [19]:
# array shape
from numpy import array
# list of data
data = [[11, 22],
		[33, 44],
		[55, 66]]
# array of data
data = array(data)
print(data.shape)

(3, 2)


In [20]:
# array shape
from numpy import array
# list of data
data = [[11, 22],
		[33, 44],
		[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


#### Reshape 1D to 2D Array

In [23]:
# reshape 1D array
from numpy import array
from numpy import reshape
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)
print(data)

(5,)
(5, 1)
[[11]
 [22]
 [33]
 [44]
 [55]]


#### Reshape 2D to 3D Array

In [25]:
# reshape 2D array
from numpy import array
# list of data
data = [[11, 22],
		[33, 44],
		[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)
print(data)

(3, 2)
(3, 2, 1)
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]
