## Numpy Library 

### [Reference] YouTube Tutorial - Keith Galli

#### Load in numpy

In [1]:
import numpy as np

#### The basics

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get dimensions
print(a.ndim)
b.ndim

1


2

In [5]:
# Get shape
a.shape

(3,)

In [6]:
b.shape

(2, 3)

In [7]:
# Get type
a.dtype

dtype('int32')

In [8]:
# Get size
a.itemsize # coz we made a - int 16 explixitly - op is 4 for int 32


4

In [9]:
# Get totsl size 
# a.size * a.itemsize == a.nbytes
a.nbytes

12

#### Accessing / changing specific elements, rows, columns etc 

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [row,col]

#a[1,5]
a[1,-2]

13

In [12]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [14]:
# Getting a lil more fancy [startindex:endindex:stepsize]

a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### 3d example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# To get a specific element (cue: work outside in)

#b[0,1,1]
#b[:,1,:]
#b[:,0,:]


In [18]:
# to replace
b[:,1,:] = [[9,9],[8,8]]
b


array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

#### Initializing different types of arrays

In [19]:
# ALl zeros matrix
#np.zeros(5)
#np.zeros((2,3))
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
# All ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [22]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [23]:
# Any other number (full-like)

np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [24]:
# or
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
# Random decimal number
np.random.rand(4,2)

array([[0.35878484, 0.911751  ],
       [0.99729775, 0.25207618],
       [0.69772664, 0.1822738 ],
       [0.2433197 , 0.01184122]])

In [26]:
# If you want to pass in a shape
np.random.random_sample(a.shape)

array([[0.08034105, 0.51406225, 0.03760932, 0.03474644, 0.24702922,
        0.38444353, 0.21056217],
       [0.4414679 , 0.15942569, 0.87791765, 0.55361215, 0.61516591,
        0.96644402, 0.92125704]])

In [27]:
# Random integer 
np.random.randint(7, size=(3,3))

array([[6, 1, 2],
       [1, 1, 1],
       [3, 1, 4]])

In [28]:
# Repeating an array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
# to get a mixed matrix

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

z[1,1] = 9
z

output[1:-1,1:-1] = z 
output

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

####  Be careful when copying arrays

In [30]:
a = np.array([1,2,3])
a
b = a.copy()
print(b)
b[1] = 99
print(b)
print(a)


# to avoid this - use .copy()


[1 2 3]
[ 1 99  3]
[1 2 3]


In [31]:
# MAth

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [32]:
a + 2


array([3, 4, 5, 6])

In [33]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [34]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [35]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear algebra

In [36]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [37]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [38]:
######Statistics

In [39]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.min(stats, axis = 1)

array([1, 4])

In [41]:
np.max(stats)

6

In [42]:
np.sum(stats)

21

In [43]:
# reorganizing arrays

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [44]:
# vertical stacking

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])



array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [45]:
# horizontal stacking

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack ((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [46]:
# misc

# load data from file 

filedata = np.genfromtext('data.txt',delimiter= ',')
filedata = filedata.astype('int32')

                     
                          

AttributeError: module 'numpy' has no attribute 'genfromtext'

In [47]:
# boolean masking and advanced indexing


filedata > 50

NameError: name 'filedata' is not defined

In [48]:
# to get indexex where value > 50

filedata[filedata > 50]

NameError: name 'filedata' is not defined

In [49]:
# you can index with a list in numpy

np.any
np.all

<function numpy.core.fromnumeric.all(a, axis=None, out=None, keepdims=<no value>)>

In [50]:
j = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(j)

#print(j[2:-2,0:-3])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [51]:
print(j[[0,1,2,3],[1,2,3,4]])

[ 2  8 14 20]


In [52]:
print(j[[0,4,5],3:])

[[ 4  5]
 [24 25]
 [29 30]]


### [Additional resources] 

https://www.geeksforgeeks.org/numpy-in-python-set-1-introduction/     

https://www.geeksforgeeks.org/numpy-python-set-2-advanced/